[project]
name = "acapy-vc-authn-oidc"
version = "0.2.2"
description = "Verifiable Credential Identity Provider for OpenID Connect."
authors = [ { name = "Government of British Columbia", email = "DItrust@gov.bc.ca" } ]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
repository = "https://github.com/openwallet-foundation/acapy-vc-authn-oidc"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi(>=0.115.12,<1.0)",
    "jinja2(>=3.1.6,<4.0)",
    "oic(>=1.7.0,<2.0)",
    "pymongo(>=4.12.1,<5.0)",
    "pyop(>=3.4.1,<4.0)",
    "python-multipart(>=0.0.20,<1.0)",
    'qrcode[pil](>=8.2,<9.0)',
    "structlog(>=25.3.0,<26.0.0)",
    'uvicorn[standard](>=0.34.2,<1)',
    "python-socketio(>=5.13.0,<6.0.0)",
    "canonicaljson(>=2.0.0,<3.0.0)",
    "pydantic-settings (>=2.9.1,<3.0)",
]

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
mock = "^5.2.0"
mongomock = "^4.3.0"
pytest-asyncio = "^0.26.0"
pytest-cov = "^6.1.1"
pytest = "^8.3.5"
requests-mock = "^1.12.1"
setuptools = "^80.3.1"
