name: Helm Chart Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  chart-release:
    name: Create and Publish Chart Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Add bitnami repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Run chart-releaser
        uses: ./.github/actions/chart_releaser
        with:
          config: .github/actions/chart_releaser/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  
  update-configs-and-sync:
    runs-on: ubuntu-latest
    name: Update Configs and Sync
    needs:
      - chart-release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout services directory from the trust-over-ip-configurations repo
        uses: actions/checkout@v4
        with:
          repository: bcgov/trust-over-ip-configurations
          ssh-key: ${{ secrets.DITP_CONFIGS_REPO_SECRET }}
          sparse-checkout: |
            services
          path: trust-over-ip-configurations

      - name: Lookup latest chart
        id: chart_version
        run: |
          helm repo add vc-authn-oidc https://bcgov.github.io/vc-authn-oidc
          helm repo update
          echo "::set output name=APP_VERSION::$(helm search repo vc-authn-oidc -ojson | jq '.[0].app_version')"
          echo "::set output name=CHART_VERSION::$(helm search repo vc-authn-oidc -ojson | jq '.[0].version')"

      - name: Update test
        env:
          APP_VERSION: ${{ steps.chart_version.outputs.APP_VERSION }}
          CHART_VERSION: ${{ steps.chart_version.outputs.CHART_VERSION }}
        run: |
          cd trust-over-ip-configurations
          yq e -i '.appVersion = $APP_VERSION' services/vc-authn-oidc/charts/test/Chart.yaml
          yq e -i '.version = $CHART_VERSION' services/vc-authn-oidc/charts/test/Chart.yaml

      - name: Update prod
        env:
          APP_VERSION: ${{ steps.chart_version.outputs.APP_VERSION }}
          CHART_VERSION: ${{ steps.chart_version.outputs.CHART_VERSION }}
        run: |
          cd trust-over-ip-configurations
          yq e -i '.appVersion = $APP_VERSION' services/vc-authn-oidc/charts/prod/Chart.yaml
          yq e -i '.version = $CHART_VERSION' services/vc-authn-oidc/charts/prod/Chart.yaml

      - name: Commit and Push to trust-over-ip-configurations Repo
        run: |
          cd trust-over-ip-configurations
          git add services/vc-authn-oidc/charts/test/Chart.yaml services/vc-authn-oidc/charts/prod/Chart.yaml
          git commit -m "Update chart and app versions" || echo "No changes to commit"
          git push origin main

      - name: Trigger and wait for GitOps sync workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        id: workflow-trigger
        with:
          owner: bcgov
          repo: trust-over-ip-configurations
          github_token: ${{ secrets.DITP_CONFIGS_REPO_TOKEN }}
          workflow_file_name: gitops_sync.yaml

      - name: Trigger ArgoCD Sync of e79518-test-vc-authn-oidc
        uses: OpsVerseIO/argocd-sync@0.2.0
        with:
          address: gitops-shared.apps.silver.devops.gov.bc.ca
          token: ${{ secrets.DITP_GITOPS_ARGO_SECRET}}
          action: sync
          appName: "e79518-test-vc-authn-oidc"
