name: Build, Update Config, and Deploy Development
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build ACAPy VC-AuthN"
    if: github.repository_owner == 'bcgov'
    uses: ./.github/workflows/publish.yml
    with:
      tag: "dev"
      ref: "main"
      platforms: "linux/amd64"

